namespace Shared.Enums.HealthConnect
{
    public enum HealthConnectRecordTypeEnum
    {
        ActiveCaloriesBurned = 0,
        BasalBodyTemperature = 1,
        BasalMetabolicRate = 2,
        BloodGlucose = 3,
        BloodPressure = 4,
        BodyFat = 5,
        BodyTemperature = 6,
        BodyWaterMass = 7,
        BoneMass = 8,
        CervicalMucus = 9,
        CyclingPedalingCadence = 10,
        Distance = 11,
        ElevationGained = 12,
        ExerciseSession = 13,
        FloorsClimbed = 14,
        HeartRate = 15,
        HeartRateVariability = 16,
        Height = 17,
        Hydration = 18,
        IntermenstrualBleeding = 19,
        LeanBodyMass = 20,
        MenstruationFlow = 21,
        MenstruationPeriod = 22,
        Nutrition = 23,
        OvulationTest = 24,
        OxygenSaturation = 25,
        Power = 26,
        RespiratoryRate = 27,
        RestingHeartRate = 28,
        SexualActivity = 29,
        SkinTemperature = 30,
        SleepSession = 31,
        Speed = 32,
        Steps = 33,
        StepsCadence = 34,
        TotalCaloriesBurned = 35,
        Vo2Max = 36,
        Weight = 37,
        WheelchairPushes = 38,
        HeartRateVariabilityRmssd = 39,
    }
}
