using System;
using System.Collections.Generic;
using System.Text;

namespace Shared.Enums.HealthConnect
{
    public enum HealthConnectExerciseSegmentTypeEnum
    {
        UNKNOWN = 0,
        BARBELL_SHOULDER_PRESS = 4,
        BENCH_SIT_UP = 6,
        BIKING = 7,
        BIKING_STATIONARY = 8,
        DUMBBELL_CURL_LEFT_ARM = 12,
        DUMBBELL_CURL_RIGHT_ARM = 13,
        DUMBBELL_FRONT_RAISE = 14,
        DUMBBELL_LATERAL_RAISE = 15,
        DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM = 16,
        DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM = 17,
        DUMBBELL_TRICEPS_EXTENSION_TWO_ARM = 18,
        FORWARD_TWIST = 19,
        ELLIPTICAL = 20,
        HIGH_INTENSITY_INTERVAL_TRAINING = 21,
        JUMPING_JACK = 22,
        JUMP_ROPE = 23,
        LAT_PULL_DOWN = 24,
        LEG_CURL = 25,
        ARM_CURL = 1,
        BACK_EXTENSION = 2,
        BALL_SLAM = 3,
        BENCH_PRESS = 5,
        BURPEE = 9,
        CRUNCH = 10,
        DEADLIFT = 11,
        LUNGE = 36,
        MOUNTAIN_CLIMBER = 37,
        OTHER_WORKOUT = 38,
        PAUSE = 39,
        PILATES = 40,
        PLANK = 41,
        PULL_UP = 42,
        PUNCH = 43,
        REST = 44,
        ROWING_MACHINE = 45,
        RUNNING = 46,
        RUNNING_TREADMILL = 47,
        SHOULDER_PRESS = 48,
        SINGLE_ARM_TRICEPS_EXTENSION = 49,
        SIT_UP = 50,
        SQUAT = 51,
        STAIR_CLIMBING = 52,
        STAIR_CLIMBING_MACHINE = 53,
        STRETCHING = 54,
        SWIMMING_BACKSTROKE = 55,
        SWIMMING_BREASTSTROKE = 56,
        SWIMMING_BUTTERFLY = 57,
        SWIMMING_FREESTYLE = 58,
        SWIMMING_MIXED = 59,
        SWIMMING_OPEN_WATER = 60,
        SWIMMING_OTHER = 61,
        SWIMMING_POOL = 62,
        UPPER_TWIST = 63,
        WALKING = 64,
        WEIGHTLIFTING = 65,
        WHEELCHAIR = 66,
        YOGA = 67,
    }
}
