namespace Shared.Enums.HealthConnect
{
    public enum HealthConnectUnitTypeEnum
    {
        Grams = 1,
        Kilograms = 2,
        Milligrams = 3,
        Micrograms = 4,
        Ounces = 5,
        Pounds = 6,
        Calories = 7,
        Kilocalories = 8,
        Joules = 9,
        Kilojoules = 10,
        Millimeters = 11,
        Centimeters = 12,
        Meters = 13,
        Kilometers = 14,
        Inches = 15,
        Feet = 16,
        Miles = 17,
        Celsius = 18,
        Fahrenheit = 19,
        Kelvin = 20,
        Milliliters = 21,
        Liters = 22,
        FluidOuncesUs = 23,
        MillimetersOfMercury = 24,
        MillimolesPerLiter = 25,
        MilligramsPerDeciliter = 26,
        Watts = 27,
        Kilowatts = 28,
        MetersPerSecond = 29,
        KilometersPerHour = 30,
        MilesPerHour = 31,
        BeatsPerMinute = 32,
        BreathsPerMinute = 33,
        StepsPerMinute = 34,
        RevolutionsPerMinute = 35,
        Percent = 36,
        Count = 37,
        Milliseconds = 38,
        Seconds = 39,
        Minutes = 40,
        MillilitersPerKilogramPerMinute = 41,
        KilocaloriesPerDay = 42,
    }
}
