namespace Shared.Enums.HealthConnect
{
    public enum HealthConnectUnitTypeEnum
    {
        Grams = 0,
        Kilograms = 1,
        Milligrams = 2,
        Micrograms = 3,
        Ounces = 4,
        Pounds = 5,
        Calories = 100,
        Kilocalories = 101,
        Joules = 102,
        Kilojoules = 103,
        Millimeters = 200,
        Centimeters = 201,
        Meters = 202,
        Kilometers = 203,
        Inches = 204,
        Feet = 205,
        Miles = 206,
        Celsius = 300,
        Fahrenheit = 301,
        Kelvin = 302,
        Milliliters = 400,
        Liters = 401,
        FluidOuncesUs = 402,
        MillimetersOfMercury = 500,
        MillimolesPerLiter = 600,
        MilligramsPerDeciliter = 601,
        Watts = 700,
        Kilowatts = 701,
        MetersPerSecond = 800,
        KilometersPerHour = 801,
        MilesPerHour = 802,
        BeatsPerMinute = 900,
        BreathsPerMinute = 901,
        StepsPerMinute = 902,
        RevolutionsPerMinute = 903,
        Percent = 1000,
        Count = 1001,
        Milliseconds = 1100,
        Seconds = 1101,
        Minutes = 1102,
        MillilitersPerKilogramPerMinute = 1200,
        KilocaloriesPerDay = 1300,
    }
}
