// <auto-generated />
using System;
using Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Database.Migrations
{
    [DbContext(typeof(AIDbContext))]
    [Migration("20260906150928_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data.Database.Entities.Ai.AiHealthConnectExerciseTrainingDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("BodyFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CaloriesBurned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("CyclingPedalingCadenceAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DistanceInMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElevationGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<decimal>("HeartRateAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("LeanBodyMass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxHeartRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinHeartRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OxygenSaturationAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PowerAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RespiratoryRatePerMinuteAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpeedAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Steps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StepsCadenceAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Vo2Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RunningTrainingDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EndTimestamp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartTimestamp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthConnectDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Scheduler.ScheduledJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestModelJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ScheduledJobsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.AISettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CanUseHealthDataAcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CanUseHealthDataForAiTraining")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CanUseHealthDataRejectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AiSettingsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.SettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AiSettingsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AiSettingsId")
                        .IsUnique();

                    b.ToTable("SettingsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserCredentialsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserCredentialsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("CredentialsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SettingsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId")
                        .IsUnique();

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectDataEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.User.UserEntity", "User")
                        .WithMany("HealthData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.SettingsEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.Settings.AISettingsEntity", "AiSettings")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.Settings.SettingsEntity", "AiSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSettings");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.User.UserCredentialsEntity", "UserCredentials")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.User.UserEntity", "CredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.Settings.SettingsEntity", "Settings")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.User.UserEntity", "SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");

                    b.Navigation("UserCredentials");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.Navigation("HealthData");
                });
#pragma warning restore 612, 618
        }
    }
}
