// <auto-generated />
using System;
using Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Database.Migrations
{
    [DbContext(typeof(AIDbContext))]
    [Migration("20260918055903_AddUserAdministrationFields")]
    partial class AddUserAdministrationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data.Database.Entities.Ai.AiTrainedModelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AiType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LogLoss")
                        .HasColumnType("double");

                    b.Property<double>("MacroAccuracy")
                        .HasColumnType("double");

                    b.Property<double>("MicroAccuracy")
                        .HasColumnType("double");

                    b.Property<byte[]>("ModelData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AiTrainedModelTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Ai.AiTrainingDataFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AiType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Csv")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool>("IsUpdated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AiTrainingDataFileTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Avg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("HealthConnectAvgTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectBloodPressureEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Diastolic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("HealthConnectValuesId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Systolic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthConnectValuesId")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("HealthConnectBloodPressureTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectHealthDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<long>("HealthConnectValuesId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataKey")
                        .IsUnique();

                    b.HasIndex("HealthConnectValuesId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("HealthConnectHealthDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectLapEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LengthInMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TrainingDataValuesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TrainingDataValuesId");

                    b.ToTable("HealthConnectLapEntity");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectSegmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("SegmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TrainingDataValuesId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TrainingDataValuesId");

                    b.ToTable("HealthConnectSegmentEntity");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTimeZoneEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Offset")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HealthConnectTimeZoneTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("AllowedForAiTraining")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<long>("HealthConnectTimeZoneEntityId")
                        .HasColumnType("bigint");

                    b.Property<long>("HealthConnectTrainingDataValuesId")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkoutIntensity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataKey")
                        .IsUnique();

                    b.HasIndex("HealthConnectTimeZoneEntityId");

                    b.HasIndex("HealthConnectTrainingDataValuesId");

                    b.HasIndex("UserId");

                    b.ToTable("HealthConnectTrainingDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ActiveCaloriesBurnedInKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("CyclingPedalingCadenceId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("DistanceInMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ElevationAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("HeartRateId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HydrationAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OxygenSaturationPercentageAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PowerId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RespiratoryRateAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RestingHeartRateId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeedId")
                        .HasColumnType("bigint");

                    b.Property<long>("StepCadenceId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Steps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Vo2MaxMlPerMinKgAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WeightAvg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CyclingPedalingCadenceId");

                    b.HasIndex("HeartRateId");

                    b.HasIndex("PowerId");

                    b.HasIndex("RestingHeartRateId");

                    b.HasIndex("SpeedId");

                    b.HasIndex("StepCadenceId");

                    b.ToTable("HealthConnectTrainingDataValuesTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectUnitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HealthConnectUnitTable");

                    b.HasData(
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 32,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 33,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 34,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 35,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 36,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 37,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 38,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 39,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 40,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 41,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 42,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 1,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 2,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 3,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 4,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 5,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 6,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 22,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 21,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 23,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 24,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 25,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 26,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 27,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 28,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 29,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 30,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 31,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 18,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 19,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 20,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 7,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 8,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 9,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 10,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 11,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 12,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 13,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 14,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 15,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 16,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            UnitType = 17,
                            UpdatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectValuesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ActiveCaloriesBurnedInKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BasalMetabolicRateInKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BodyFatPercentageAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("FloorsClimbed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("HeartRateId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("HeightInMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HydrationAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OxygenSaturationPercentageAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RespiratoryRateAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RestingHeartRateId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SleepDurationInSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Steps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCaloriesBurnedInKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Vo2MaxMlPerMinKgAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WheelchairPushes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HeartRateId");

                    b.HasIndex("RestingHeartRateId");

                    b.ToTable("HealthConnectValuesTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Nutrition.NutritionDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<long>("NutritionValuesId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataKey")
                        .IsUnique();

                    b.HasIndex("NutritionValuesId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("NutritionDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Nutrition.NutritionValuesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CaloriesKcal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CarbohydratesGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("FatGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FiberGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProteinGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SugarGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NutritionValuesTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Scheduler.ScheduledJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestModelJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ScheduledJobsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.AISettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CanUseHealthDataAcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CanUseHealthDataForAiTraining")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CanUseHealthDataRejectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AiSettingsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.SettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AiSettingsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AiSettingsId")
                        .IsUnique();

                    b.ToTable("SettingsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserBodyDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Abdomen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BodyFatPercentageAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CanUpdateBodyFatPercentageOnHealthDataImport")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanUpdateWeightOnHealthDataImport")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBodyDataTable");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserCredentialsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserCredentialsTable");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("CredentialsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SettingsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("CredentialsId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectUnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectBloodPressureEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectValuesEntity", "Values")
                        .WithOne("BloodPressure")
                        .HasForeignKey("Data.Database.Entities.HealthConnect.HealthConnectBloodPressureEntity", "HealthConnectValuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectUnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectHealthDataEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectValuesEntity", "Values")
                        .WithOne("Record")
                        .HasForeignKey("Data.Database.Entities.HealthConnect.HealthConnectHealthDataEntity", "HealthConnectValuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.User.UserEntity", "User")
                        .WithMany("HealthData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectLapEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", "TrainingDataValue")
                        .WithMany("Laps")
                        .HasForeignKey("TrainingDataValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingDataValue");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectSegmentEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", "TrainingDataValue")
                        .WithMany("Segments")
                        .HasForeignKey("TrainingDataValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingDataValue");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectTimeZoneEntity", "HealthConnectTimeZoneEntity")
                        .WithMany()
                        .HasForeignKey("HealthConnectTimeZoneEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", "HealthConnectTrainingDataValues")
                        .WithMany()
                        .HasForeignKey("HealthConnectTrainingDataValuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.User.UserEntity", "User")
                        .WithMany("TrainingData")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HealthConnectTimeZoneEntity");

                    b.Navigation("HealthConnectTrainingDataValues");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "CyclingPedalingCadence")
                        .WithMany()
                        .HasForeignKey("CyclingPedalingCadenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "HeartRate")
                        .WithMany()
                        .HasForeignKey("HeartRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "Power")
                        .WithMany()
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "RestingHeartRate")
                        .WithMany()
                        .HasForeignKey("RestingHeartRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "Speed")
                        .WithMany()
                        .HasForeignKey("SpeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "StepCadence")
                        .WithMany()
                        .HasForeignKey("StepCadenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HealthConnectTrainingDataValuesTable_HealthConnectAvgTable_~1");

                    b.Navigation("CyclingPedalingCadence");

                    b.Navigation("HeartRate");

                    b.Navigation("Power");

                    b.Navigation("RestingHeartRate");

                    b.Navigation("Speed");

                    b.Navigation("StepCadence");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectValuesEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "HeartRate")
                        .WithMany()
                        .HasForeignKey("HeartRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.HealthConnect.HealthConnectAvgEntity", "RestingHeartRate")
                        .WithMany()
                        .HasForeignKey("RestingHeartRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeartRate");

                    b.Navigation("RestingHeartRate");
                });

            modelBuilder.Entity("Data.Database.Entities.Nutrition.NutritionDataEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.Nutrition.NutritionValuesEntity", "Values")
                        .WithOne("Record")
                        .HasForeignKey("Data.Database.Entities.Nutrition.NutritionDataEntity", "NutritionValuesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Data.Database.Entities.Settings.SettingsEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.Settings.AISettingsEntity", "AiSettings")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.Settings.SettingsEntity", "AiSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSettings");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserBodyDataEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.User.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.User.UserBodyDataEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.HasOne("Data.Database.Entities.User.UserCredentialsEntity", "UserCredentials")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.User.UserEntity", "CredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Database.Entities.Settings.SettingsEntity", "Settings")
                        .WithOne()
                        .HasForeignKey("Data.Database.Entities.User.UserEntity", "SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");

                    b.Navigation("UserCredentials");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectTrainingDataValuesEntity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Data.Database.Entities.HealthConnect.HealthConnectValuesEntity", b =>
                {
                    b.Navigation("BloodPressure");

                    b.Navigation("Record")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Database.Entities.Nutrition.NutritionValuesEntity", b =>
                {
                    b.Navigation("Record")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Database.Entities.User.UserEntity", b =>
                {
                    b.Navigation("HealthData");

                    b.Navigation("TrainingData");
                });
#pragma warning restore 612, 618
        }
    }
}
